package com.set.challenge.one;

import java.util.HashSet;
import java.util.Set;

public class HeavenlyBody {
	private final String name;
	private final double orbitalDuration;
	private final Set<HeavenlyBody> satellites;
	private final Type bodyType;
	
	public HeavenlyBody(String name, double orbitalDuration, Type bodyType) {
		this.name = name;
		this.orbitalDuration = orbitalDuration;
		this.bodyType = bodyType;
		this.satellites = new HashSet<>();
	}

	public boolean addSatellite(HeavenlyBody moon) {
		return this.satellites.add(moon);
	}
	
	
	public Type getBodyType() {
		return bodyType;
	}


	public String getName() {
		return name;
	}

	public double getOrbitalDuration() {
		return orbitalDuration;
	}

	public Set<HeavenlyBody> getSatellites() {
		return new HashSet<>(this.satellites);
	}

	
	/**
	 *	We should override both equals() and hashcode() when using object 
	 *	as elements in Set or as key in Map to avoid 
	 *	unexpected behavior and avoid duplicates
	 *
	 *
	 *	Need to make the method final because it have subclasses and to avoid breaking the 
	 *	equals() contract as the subclasses may inadvertently override the equals() breaking the contract
	 */
	@Override
	public final boolean equals(Object obj) {
		//System.out.println("equals() called");
		
		/* This is the default implementation given by Eclipse generator.
		 * 
		 * if (this == obj) return true; if (obj == null) return false; if (getClass()
		 * != obj.getClass()) return false; HeavenlyBody other = (HeavenlyBody) obj; if
		 * (name == null) { if (other.name != null) return false; } else if
		 * (!name.equals(other.name)) return false; return true;
		 */
		
		if(this == obj) { 
			return true;
		} 
	
		if(obj != null || obj instanceof HeavenlyBody) {
			HeavenlyBody theBody = ((HeavenlyBody)obj);
			if(this.getName().equals(theBody.getName())) {
				return this.getBodyType() == theBody.getBodyType();
			}
		} 
			return false;
		
	}
	
	/*
	 * If the equals() is final hashcode() also has to be final as per the contract
	 */
	
	@Override
	public final int hashCode() {
		/* Default implementation generated by Eclipse
		 * 
		 * final int prime = 31; 
		 * int result = 1; 
		 * result = prime * result + ((name == null) ? 0 : name.hashCode()); 
		 * return result;
		 */
		//System.out.println("hasCode() called ");
		// 51 is any integer no within the range of integer.
		
											// this part is required because as per our challenge, we are determining 
											// uniqueness based on designation and not name alone
		return this.getName().hashCode() + 51 + this.getBodyType().hashCode();
	}

	@Override
	public String toString() {
		return name + ", " + orbitalDuration + ", " + bodyType;
	}
	
	
	
	
}
